//
//  SalesReport.swift
//  AppStats
//
//  Created by Alfred Lieth Årøe on 03/12/2023.
//

import Foundation
import SwiftCSV

// I wish these were autogenerated, but unfortunetly not since the response from apple is a tarball...
enum SalesReportSales: String {
    case provider = "Provider"
    case providerCountry = "Provider Country"
    case sku = "SKU"
    case developer = "Developer"
    case title = "Title"
    case version = "Version"
    case productTypeIdentifier = "Product Type Identifier"
    case units = "Units"
    case developerProceeds = "Developer Proceeds"
    case beginDate = "Begin Date"
    case endDate = "End Date"
    case customerCurrency = "Customer Currency"
    case countryCode = "Country Code"
    case currencyOfProceeds = "Currency of Proceeds"
    case appleIdentifier = "Apple Identifier"
    case customerPrice = "Customer Price"
    case promoCode = "Promo Code"
    case parentIdentifier = "Parent Identifier"
    case subscription = "Subscription"
    case period = "Period"
    case category = "Category"
    case cmb = "CMB"
    case device = "Device"
    case supportedPlatforms = "Supported Platforms"
    case proceedsReason = "Proceeds Reason"
    case preservedPricing = "Preserved Pricing"
    case client = "Client"
    case orderType = "Order Type"
}

enum SalesReportSubscriptionFields: String, CodingKey {
    case appName = "App Name"
    case appAppleId = "App Apple ID"
    case subscriptionName = "Subscription Name"
    case subscriptionAppleId = "Subscription Apple ID"
    case subscriptionGroupId = "Subscription Group ID"
    case standardSubscriptionDuration = "Standard Subscription Duration"
    case subscriptionOfferName = "Subscription Offer Name"
    case promotionalOfferId = "Promotional Offer ID"
    case customerPrice = "Customer Price"
    case customerCurrency = "Customer Currency"
    case developerProceeds = "Developer Proceeds"
    case proceedsCurrency = "Proceeds Currency"
    case preservedPricing = "Preserved Pricing"
    case proceedsReason = "Proceeds Reason"
    case client = "Client"
    case device = "Device"
    case state = "State"
    case country = "Country"
    case activeStandardPriceSubscriptions = "Active Standard Price Subscriptions"
    case activeFreeTrialIntroductoryOfferSubscriptions = "Active Free Trial Introductory Offer Subscriptions"
    case activePayUpFrontIntroductoryOfferSubscriptions = "Active Pay Up Front Introductory Offer Subscriptions"
    case activePayAsYouGoIntroductoryOfferSubscriptions = "Active Pay As You Go Introductory Offer Subscriptions"
    case freeTrialPromotionalOfferSubscriptions = "Free Trial Promotional Offer Subscriptions"
    case payUpFrontPromotionalOfferSubscriptions = "Pay Up Front Promotional Offer Subscriptions"
    case payAsYouGoPromotionalOfferSubscriptions = "Pay As You Go Promotional Offer Subscriptions"
    case freeTrialOfferCodeSubscriptions = "Free Trial Offer Code Subscriptions"
    case payUpFrontOfferCodeSubscriptions = "Pay Up Front Offer Code Subscriptions"
    case payAsYouGoOfferCodeSubscriptions = "Pay As You Go Offer Code Subscriptions"
    case marketingOptIns = "Marketing Opt-Ins"
    case billingRetry = "Billing Retry"
    case gracePeriod = "Grace Period"
    case subscribers = "Subscribers"
}

struct SalesReportSubscription: Decodable {
    let appName: String
    let appAppleId: Int
    let subscriptionName: String
    let subscriptionAppleId: Int
    let subscriptionGroupId: Int
    let standardSubscriptionDuration: String
    let subscriptionOfferName: String
    let promotionalOfferId: String
    let customerPrice: Double
    let customerCurrency: String
    let developerProceeds: Double
    let proceedsCurrency: String
    let preservedPricing: String
    let proceedsReason: String
    let client: String
    let device: String
    let state: String
    let country: String
    let activeStandardPriceSubscriptions: Int
    let activeFreeTrialIntroductoryOfferSubscriptions: Int
    let activePayUpFrontIntroductoryOfferSubscriptions: Int
    let activePayAsYouGoIntroductoryOfferSubscriptions: Int
    let freeTrialPromotionalOfferSubscriptions: Int
    let payUpFrontPromotionalOfferSubscriptions: Int
    let payAsYouGoPromotionalOfferSubscriptions: Int
    let freeTrialOfferCodeSubscriptions: Int
    let payUpFrontOfferCodeSubscriptions: Int
    let payAsYouGoOfferCodeSubscriptions: Int
    let marketingOptIns: Int
    let billingRetry: Int
    let gracePeriod: Int
    var subscribers: Double
    
    init(subscribers: Double, country: String, subscriptionName: String) {
        self.appName = ""
        self.appAppleId = 0
        self.subscriptionName = subscriptionName
        self.subscriptionAppleId = 0
        self.subscriptionGroupId = 0
        self.standardSubscriptionDuration = ""
        self.subscriptionOfferName = ""
        self.promotionalOfferId = ""
        self.customerPrice = 0.0
        self.customerCurrency = ""
        self.developerProceeds = 0.0
        self.proceedsCurrency = ""
        self.preservedPricing = ""
        self.proceedsReason = ""
        self.client = ""
        self.device = ""
        self.state = ""
        self.country = country
        self.activeStandardPriceSubscriptions = 0
        self.activeFreeTrialIntroductoryOfferSubscriptions = 0
        self.activePayUpFrontIntroductoryOfferSubscriptions = 0
        self.activePayAsYouGoIntroductoryOfferSubscriptions = 0
        self.freeTrialPromotionalOfferSubscriptions = 0
        self.payUpFrontPromotionalOfferSubscriptions = 0
        self.payAsYouGoPromotionalOfferSubscriptions = 0
        self.freeTrialOfferCodeSubscriptions = 0
        self.payUpFrontOfferCodeSubscriptions = 0
        self.payAsYouGoOfferCodeSubscriptions = 0
        self.marketingOptIns = 0
        self.billingRetry = 0
        self.gracePeriod = 0
        self.subscribers = subscribers
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: SalesReportSubscriptionFields.self)

        // Initialize properties using the enum cases
        self.appName = try container.decodeIfPresent(String.self, forKey: .appName) ?? ""
        self.appAppleId = try container.decodeIfPresent(Int.self, forKey: .appAppleId) ?? 0
        self.subscriptionName = try container.decodeIfPresent(String.self, forKey: .subscriptionName) ?? ""
        self.subscriptionAppleId = try container.decodeIfPresent(Int.self, forKey: .subscriptionAppleId) ?? 0
        self.subscriptionGroupId = try container.decodeIfPresent(Int.self, forKey: .subscriptionGroupId) ?? 0
        self.standardSubscriptionDuration = try container.decodeIfPresent(String.self, forKey: .standardSubscriptionDuration) ?? ""
        self.subscriptionOfferName = try container.decodeIfPresent(String.self, forKey: .subscriptionOfferName) ?? ""
        self.promotionalOfferId = try container.decodeIfPresent(String.self, forKey: .promotionalOfferId) ?? ""
        self.customerPrice = try container.decodeIfPresent(Double.self, forKey: .customerPrice) ?? 0.0
        self.customerCurrency = try container.decodeIfPresent(String.self, forKey: .customerCurrency) ?? ""
        self.developerProceeds = try container.decodeIfPresent(Double.self, forKey: .developerProceeds) ?? 0.0
        self.proceedsCurrency = try container.decodeIfPresent(String.self, forKey: .proceedsCurrency) ?? ""
        self.preservedPricing = try container.decodeIfPresent(String.self, forKey: .preservedPricing) ?? ""
        self.proceedsReason = try container.decodeIfPresent(String.self, forKey: .proceedsReason) ?? ""
        self.client = try container.decodeIfPresent(String.self, forKey: .client) ?? ""
        self.device = try container.decodeIfPresent(String.self, forKey: .device) ?? ""
        self.state = try container.decodeIfPresent(String.self, forKey: .state) ?? ""
        self.country = try container.decodeIfPresent(String.self, forKey: .country) ?? ""
        self.activeStandardPriceSubscriptions = try container.decodeIfPresent(Int.self, forKey: .activeStandardPriceSubscriptions) ?? 0
        self.activeFreeTrialIntroductoryOfferSubscriptions = try container.decodeIfPresent(Int.self, forKey: .activeFreeTrialIntroductoryOfferSubscriptions) ?? 0
        self.activePayUpFrontIntroductoryOfferSubscriptions = try container.decodeIfPresent(Int.self, forKey: .activePayUpFrontIntroductoryOfferSubscriptions) ?? 0
        self.activePayAsYouGoIntroductoryOfferSubscriptions = try container.decodeIfPresent(Int.self, forKey: .activePayAsYouGoIntroductoryOfferSubscriptions) ?? 0
        self.freeTrialPromotionalOfferSubscriptions = try container.decodeIfPresent(Int.self, forKey: .freeTrialPromotionalOfferSubscriptions) ?? 0
        self.payUpFrontPromotionalOfferSubscriptions = try container.decodeIfPresent(Int.self, forKey: .payUpFrontPromotionalOfferSubscriptions) ?? 0
        self.payAsYouGoPromotionalOfferSubscriptions = try container.decodeIfPresent(Int.self, forKey: .payAsYouGoPromotionalOfferSubscriptions) ?? 0
        self.freeTrialOfferCodeSubscriptions = try container.decodeIfPresent(Int.self, forKey: .freeTrialOfferCodeSubscriptions) ?? 0
        self.payUpFrontOfferCodeSubscriptions = try container.decodeIfPresent(Int.self, forKey: .payUpFrontOfferCodeSubscriptions) ?? 0
        self.payAsYouGoOfferCodeSubscriptions = try container.decodeIfPresent(Int.self, forKey: .payAsYouGoOfferCodeSubscriptions) ?? 0
        self.marketingOptIns = try container.decodeIfPresent(Int.self, forKey: .marketingOptIns) ?? 0
        self.billingRetry = try container.decodeIfPresent(Int.self, forKey: .billingRetry) ?? 0
        self.gracePeriod = try container.decodeIfPresent(Int.self, forKey: .gracePeriod) ?? 0
        self.subscribers = try container.decodeIfPresent(Double.self, forKey: .subscribers) ?? 0.0
    }
}


    


struct SubscriptionReport: Identifiable {
    var report: SalesReportSubscription
    let date: Date
    var id: String
    
    init(reportRow: Named.Row, date: Date) throws {
        let salesReport = try JSONDecoder().decode(SalesReportSubscription.self, from: JSONSerialization.data(withJSONObject: reportRow))

        // let decoder = JSONDecoder()
        // decoder.keyDecodingStrategy = .convertFromSnakeCase  // Use the appropriate strategy based on your data
        // let yourStructInstance = try decoder.decode(SalesReportSubscription.self, from: JSONSerialization.data(withJSONObject: reportRow))
        
        self.report = salesReport
        self.date = date
        self.id = date.ISO8601Format() + salesReport.device + salesReport.country + salesReport.subscriptionName
    }
    
    init(report: SalesReportSubscription, date: Date) {
        self.report = report
        self.date = date
        self.id = date.ISO8601Format() + report.device + report.country + report.subscriptionName
    }
}

// Simplified internal state
struct ActiveSubscribers: Identifiable {
    var subscribers: Int
    let date: Date
    let country: String
    let subscriptionName: String
    var id: String { subscriptionName }
}

